require:
  - rubocop-rails
AllCops:
  Exclude:
    - Guardfile
    - vendor/**/*
    - bin/**
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - tmp/**/*
    - public/**/*
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.2
